version: '3'
services:      
  edgify-on-screen-app:
    restart: always
    container_name: edgify-on-screen-app
    image: edgify/edgify-on-screen-app
    privileged: true
    environment:
      - DISPLAY=unix${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
#      - /edgify_on_screen_app/config.json:/app/config.json
    network_mode: host
